/**
 * Worker entry: OpenNext's generated Next.js handler, plus a scheduled()
 * handler that replaces the Vercel cron.
 *
 * The daily report stays a normal route (/api/cron/daily-report/) with its own
 * CRON_SECRET check; the cron trigger just calls it in-process, through the
 * same fetch handler a visitor would hit. One code path, testable with curl.
 */

// Generated by `opennextjs-cloudflare build`; this file is bundled by wrangler, not type-checked by Next.
import { default as nextHandler } from "../.open-next/worker.js";
import { canonicalRedirect } from "./canonical";
import { browserCacheControl } from "./cache-headers";

type Env = { CRON_SECRET?: string } & Record<string, unknown>;

export default {
  /**
   * mojicap.com and http:// answer 308 to https://www before Next boots.
   * Pages leave with a browser-safe Cache-Control (see cache-headers.ts).
   */
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const target = canonicalRedirect(request.url);
    if (target) return Response.redirect(target, 308);
    const response: Response = await nextHandler.fetch(request, env, ctx);
    const cacheControl = browserCacheControl(response.headers.get("cache-control"), response.headers.get("content-type"));
    if (!cacheControl) return response;
    const rewritten = new Response(response.body, response);
    rewritten.headers.set("cache-control", cacheControl);
    return rewritten;
  },

  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    const secret = env.CRON_SECRET;
    if (!secret) {
      console.error("[cron:daily-report] CRON_SECRET is not set; skipped");
      return;
    }
    const request = new Request("https://www.mojicap.com/api/cron/daily-report/", {
      headers: { authorization: `Bearer ${secret}` },
    });
    const response: Response = await nextHandler.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) throw new Error(`daily report failed: ${response.status} ${body.slice(0, 300)}`);
    console.info("[cron:daily-report]", body.slice(0, 300));
  },
} satisfies ExportedHandler<Env>;
