/**
 * Waffo product ids per SKU — GENERATED by scripts/waffo-setup.mjs, do not edit
 * by hand. An empty string means the product has not been created in Waffo
 * yet; checkout for that SKU fails fast with a clear error.
 *
 * Regenerate after creating or changing products:
 *   WAFFO_MERCHANT_ID=MER_… WAFFO_STORE_ID=STO_… WAFFO_PRIVATE_KEY_FILE=./waffo-private.pem \
 *     node scripts/waffo-setup.mjs --write
 */
export const WAFFO_PRODUCT_IDS: Record<string, string> = {
  plus_monthly: "PROD_186uzVQPL0VATZQFYS9ArA",
  plus_yearly: "PROD_3wmciRYKhSdgyITruU7RXp",
  plus_monthly_cn: "PROD_4LljfyiTVxGKbt74IEOPVt",
  plus_yearly_cn: "PROD_3mqwhYH0oXbaL6AawmNqn7",
};
